/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    EmailForm: typeof import('./src/components/EmailForm.vue')['default']
    IHeroiconsArrowRight: typeof import('~icons/heroicons/arrow-right')['default']
    IHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
    IHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IHeroiconsExclamationCircle: typeof import('~icons/heroicons/exclamation-circle')['default']
    IHeroiconsMegaphone: typeof import('~icons/heroicons/megaphone')['default']
    IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
    IMdiLoading: typeof import('~icons/mdi/loading')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    VolunteerBanner: typeof import('./src/components/VolunteerBanner.vue')['default']
    VolunteerItem: typeof import('./src/components/VolunteerItem.vue')['default']
  }
}

// For TSX support
declare global {
  const ContactForm: typeof import('./src/components/ContactForm.vue')['default']
  const Disclosure: typeof import('@headlessui/vue')['Disclosure']
  const DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
  const DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
  const EmailForm: typeof import('./src/components/EmailForm.vue')['default']
  const IHeroiconsArrowRight: typeof import('~icons/heroicons/arrow-right')['default']
  const IHeroiconsBars3: typeof import('~icons/heroicons/bars3')['default']
  const IHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
  const IHeroiconsExclamationCircle: typeof import('~icons/heroicons/exclamation-circle')['default']
  const IHeroiconsMegaphone: typeof import('~icons/heroicons/megaphone')['default']
  const IHeroiconsXMark: typeof import('~icons/heroicons/x-mark')['default']
  const IMdiLoading: typeof import('~icons/mdi/loading')['default']
  const NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
  const Popover: typeof import('@headlessui/vue')['Popover']
  const PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
  const PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
  const VolunteerBanner: typeof import('./src/components/VolunteerBanner.vue')['default']
  const VolunteerItem: typeof import('./src/components/VolunteerItem.vue')['default']
}