/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    DogImages: typeof import('./src/components/DogImages.vue')['default']
    EmailForm: typeof import('./src/components/EmailForm.vue')['default']
    IHeroiconsChevronDown: typeof import('~icons/heroicons/chevron-down')['default']
    IHeroiconsExclamationCircle: typeof import('~icons/heroicons/exclamation-circle')['default']
    IHeroiconsMegaphone: typeof import('~icons/heroicons/megaphone')['default']
    IMdiLoading: typeof import('~icons/mdi/loading')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    OldPhotos: typeof import('./src/components/OldPhotos.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    VolunteerBanner: typeof import('./src/components/VolunteerBanner.vue')['default']
    VolunteerItem: typeof import('./src/components/VolunteerItem.vue')['default']
  }
}
