backend:
  name: github
  repo: friends-of-ute-valley-park/friends-of-ute-valley
  branch: main

media_folder: public/images
public_folder: /images

collections:
  - name: 'news'
    label: 'News'
    folder: '/src/data/news'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: false }
      - { label: 'Published On', name: 'publishedOn', widget: 'datetime' }
      - { label: 'Cover Image', name: 'coverImage', widget: 'image', media_folder: '/src/data/news/' }
      - { label: 'Preview Text', name: 'previewText', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'volunteer'
    label: 'Volunteer'
    folder: '/src/data/events'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Short Description', name: 'description', widget: 'text', hint: 'Provide 1 sentence to preview the event on the page and social media' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
      - label: 'Meeting Location'
        name: 'meetingLocation'
        widget: 'object'
        summary: '{{fields.predefinedLocation}}'
        fields:
          - label: 'Predefined Location'
            name: 'predefinedLocation'
            widget: 'select'
            options:
              - { label: 'Other (please fill in the alternative field below)', value: -1 }
              - { label: 'Vindicator', value: 1 }
              - { label: 'South Rockrimmon', value: 2 }
              - { label: 'Tech Center', value: 3 }
              - { label: 'Piñon Valley', value: 4 }
              - { label: 'Popes Valley', value: 5 }
          - { label: 'Alternative Location', name: 'alternativeLocation', widget: 'string', required: false }
          - { label: 'Alternative Location Maps Link', name: 'alternativeLocationDirectionsLink', widget: 'string', required: false }
          - { label: 'Location Notes', name: 'notes', widget: 'text', hint: 'If necessary, provide additional info such as "at the top of the hill"', required: false }
      - { label: 'Link', name: 'link', widget: 'string', required: false }
      - { label: 'Time', name: 'time', widget: 'string' }
  - name: 'Links'
    label: 'Links'
    folder: '/src/data/links'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Priority', name: 'priority', widget: 'number', valueType: 'int', default: 0 }
  - name: 'Wishlist'
    label: 'Wishlist'
    folder: '/src/data/wishlist'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Link', name: 'link', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', media_folder: '/src/data/wishlist/' }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }
      - { label: 'QuantityNeeded', name: 'quantityNeeded', widget: 'number', valueType: 'int', default: 1 }
